name: TFPLAN

on:
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/aws/INT/us-east-1/**"]

jobs:
  tf_plan:
    name: TF-plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Source
        uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: set --cone terraform/aws/INT/us-east-1
      - name: List folder content
        run: ls -al terraform/aws/INT/us-east-1
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
#      - name: Test AWS
#        run: aws s3 ls
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/aws/INT/us-east-1
#      - name: terraform apply
#        uses: dflook/terraform-apply@v1
#        with:
#          path: terraform/aws/INT/us-east-1


